/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package iu;

/**
 *
 * @author leonel
 */
public class JF_Alumnos extends javax.swing.JInternalFrame
{
    JPanel_Alumnos_Alta jPanel_Alumnos_Alta;

    /**
     * Creates new form JF_Alumnos
     */
    public JF_Alumnos()
    {
        initComponents();
        jPanel_Alumnos_Alta = new JPanel_Alumnos_Alta();
        jPanel_Alumnos_Alta.setVisible(true);
        getContentPane().add(jPanel_Alumnos_Alta);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
