/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package iu;

import negocio.Sistema;

/**
 *
 * @author leonel
 */
public class JF_Recomendaciones extends javax.swing.JInternalFrame
{
    JPanel_Recomendaciones jPanel_Recomendaciones;
    /**
     * Creates new form JF_Recomendaciones
     */
    public JF_Recomendaciones()
    {
        initComponents();
        jPanel_Recomendaciones = new JPanel_Recomendaciones();
        jPanel_Recomendaciones.setVisible(true);
        getContentPane().add(jPanel_Recomendaciones);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
